### ISSUE TITLE
deepseq and WHNF form

### ISSUE THREAD

**Issue by massimo-zaniboni** [fpco/safe-exceptions#18]
I'm rather sure (but not 100%) that a good resource management library had to force a WHNF result for `bracket` and related functions, using `deepseq` or similar functions, because otherwise if the result contains unevaluated thunks, then when the thunks are evaluated at run-time, the required resources could be already closed from the `bracket` closing function.

More details on http://another-ticket-in-the-wall.blogspot.it/2016/10/raii-programming-in-haskell.html and https://github.com/massimo-zaniboni/ghc_lazy_file_content_error 

I'm not expert like you of Haskell, but if these notes make sense I can help you with testing and related low level tasks, because I'm using Haskell in production, and I would like to use your library for creating a more robust application.

In particular as first step, I can implement some test like in https://github.com/massimo-zaniboni/ghc_lazy_file_content_error , but using your library, for exposing the bad behaviour.

**Comment by snoyberg** [comment]
I haven't read the referenced links, but in general it's certainly possible
to leak resources outside of a bracket call. This isn't limited to lazy
I/O, you can trivially leak a Handle, for example. I don't think any
functions around deepseq would be relevant here.

**Comment by snoyberg** [comment]
No follow-up to previous comment, closing.
