### ISSUE TITLE
Control.Exception.Safe.Checked

### ISSUE THREAD

**Issue by mitchellwrosen** [fpco/safe-exceptions#20]
I can't remember if I've asked about this before, but would it be appropriate to incorporate the `Throws` machinery from https://www.well-typed.com/blog/2015/07/checked-exceptions/ into this library?

**Comment by snoyberg** [comment]
I'm not terribly familiar with that approach - I read the blog post and have worked with hackage-security, but that's it - but overall I'm 👎. It falls into the same trap as `ExceptT IO` AFAICT: it gives a false sense of security about which exceptions can be thrown.

**Comment by mitchellwrosen** [comment]
That's certainly true - not a panacea, and similar to `ExceptT IO` for sync exceptions. However, multiple exception types would manifest as multiple `Throws` constraints, rather than multiple layers of `ExceptT`, which is much more palatable.

I think it'd be nice to use `Throws` in a custom prelude - certainly functions in `base` can be re-exported with proper `Throws` constraints, so at least 

Also, I think it is capable of demarcating one class of partiality in a way that `ExcepT IO` can't - impure exceptions. Since of course _any_ thunk might be a bomb, you can at least sanely code around the existing, well-known partial functions with e.g.

```haskell
impureThrow :: (Exception e, ThrowsImpure e) => e -> a
impureCatch :: (Exception e, MonadCatch m, NFData a) => (ThrowsImpure e => m a) -> (e -> m a) -> m a
```

(for example, `UnicodeException` thrown by `decodeUtf8`). Anyways, I don't have any experience with this machinery, but I want to try it out. Happy to fork off a new package in the meantime.

**Comment by snoyberg** [comment]
I'd say starting in a separate package makes more sense. I'd like to keep this package with known-best practices that I can solidly recommend to anyone without concern of confusing mixed messages. If it turns out that the `Throws` approach is good, I'd be open to updating what the recommended practices are.

**Comment by mitchellwrosen** [comment]
:+1:

**Comment by mitchellwrosen** [comment]
Up at https://hackage.haskell.org/package/safe-exceptions-checked
