### ISSUE TITLE
Dead link in bracketOnError_ haddock

### ISSUE THREAD

**Issue by chris-martin** [fpco/safe-exceptions#23]
The `bracketOnError_` doc says

>     Async safe version of 'E.bracketOnError_'

https://github.com/fpco/safe-exceptions/blob/b282ec177b8a4ab056be3ddcc731fdb9ce416050/src/Control/Exception/Safe.hs#L434

But `Control.Exception` doesn't seem to export such a function ([neither does anything else](https://www.stackage.org/lts-8.5/hoogle?q=bracketOnError_)).

**Comment by snoyberg** [comment]
Want to send a PR with a better description?
