### ISSUE TITLE
Link to documentation

### ISSUE THREAD

**Issue by ivan-m** [fpco/safe-exceptions#26]
The README for this package is used as a tutorial on haskell-lang, which is linked to from blog posts, etc (rather than linking to the library itself somewhere).  However, there is no link from there to either Stackage or Hackage to be able to actually view the library documentation so you can get an idea on how to use it.

**Comment by snoyberg** [comment]
Would you be able to send a PR to add a link?

**Comment by ivan-m** [comment]
I can; would you be amenable to both Hackage and Stackage links or would you prefer just the latter?

(I thought maybe just extra badges on top as haskell-lang shows the Travis badge already.)

**Comment by snoyberg** [comment]
I'd prefer just Stackage, I still don't trust Hackage's doc builder to
reliable build the documentation and don't want to confuse people with a
choice where one path may be a dead end.
