### ISSUE TITLE
finally and bracket don't work with ExceptT

### ISSUE THREAD

**Issue by delfigamer** [fpco/safe-exceptions#36]
https://github.com/fpco/safe-exceptions/blob/9d8baf8e086591995916eae2cbae39f684326002/src/Control/Exception/Safe.hs#L428-L449

If the underlying monad is `ExceptT`, and the interior action performs `throwError`, then the release action gets skipped.

This can be checked with this test:
```hs

    describe "bracketWithError" $ do
      it "should lift through ExceptT properly" $ do
        ref <- newIORef ("no resource" :: Text)
        _ <-
          runExceptT $
            Control.Exception.Safe.bracketWithError
              ( do
                  lift $ readIORef ref `shouldReturn` "no resource"
                  lift $ writeIORef ref "resource acquired"
              )
              ( \_ () -> do
                  lift $ readIORef ref `shouldReturn` "resource used"
                  lift $ writeIORef ref "resource released"
              )
              (\() -> do
                  lift $ readIORef ref `shouldReturn` "resource acquired"
                  lift $ writeIORef ref "resource used"
                  throwError ControlledException
              )
          :: IO (Either ControlledException Void)
        readIORef ref `shouldReturn` "resource released"
```

With the current version (0.1.7.1), this test fails with `expected: "resource released", but got: "resource used"`.

Since `finally` and `bracket` are written as special cases of `bracketOnError`, they get affected by this bug as well.

As this library is using `exceptions`'s monad typeclasses, I think this function should be re-written in terms of [`generalBracket`](https://hackage.haskell.org/package/exceptions-0.10.4/docs/Control-Monad-Catch.html#v:generalBracket), so that it would handle the `ExceptT` transformer too.

**Comment by snoyberg** [comment]
Seems like a reasonable change, interested in sending a PR?
