### ISSUE TITLE
Naming of the synchronous monadic throwing function

### ISSUE THREAD

**Issue by snoyberg** [fpco/safe-exceptions#4]
Raised by @Gabriel439 on Twitter. The current implementation of this library uses the name `throw` for this purpose. Pro: it's the primary action people will want with runtime exceptions (in contrast to `Control.Exception.throw` which is impure, and `throwTo` which is the much less used asynchronous exceptions). Con: it conflicts with the naming in `Control.Exception`. My initial opinion was that conflicting with naming from base is OK, since we're trying to establish the correct way of doing things in this library, and all other functions _also_ have a slight difference in behavior from `Control.Exception`.

Possible alternatives:

* Remove the `throw` function, and recommend either `throwIO` or `throwM` (both already exist as synonyms for `throw`)
* Mark `throw` as deprecated perhaps?
* Change to a totally different nomenclature (like `raise`, `die`, or [`yolo`](https://twitter.com/danclien/status/745634915455139840)

Ultimately, this is just a naming issue and not a semantic issue, but it's best to get it right from the start if possible.

**Comment by ndmitchell** [comment]
I view the conflict with throw as desirable. If people inadvertently have both in scope then it doesn't work, which is great. In practice I think I'd always use throwIO, but the throw is useful too. Another word just confuses everything. 

PS. Awesome library, good design decisions.

**Comment by da-x** [comment]
How about `fallback` or `unwind`? Maybe add suffix `With`?

**Comment by Gabriel439** [comment]
I think my original objection was minor.  I'm not that opposed to `throw` so it's okay if you keep it.  I think it would only be worth renaming if there was a similarly nice name we could use

**Comment by snoyberg** [comment]
OK, closing as wontfix.
