### ISSUE TITLE
Add HasCallStack to functions

### ISSUE THREAD

**Issue by tbidne** [fpco/safe-exceptions#40]
`exceptions` added `HasCallStack` to some of its functions in 0.10.6 in these two PRs:

* https://github.com/ekmett/exceptions/pull/90
* https://github.com/ekmett/exceptions/pull/92

I wonder if a PR similar to the second one would be accepted here? E.g. something like

```haskell
#if __GLASGOW_HASKELL__ >= 800
# define HAS_CALL_STACK HasCallStack
#else
# define HAS_CALL_STACK ()

throwM :: HAS_CALL_STACK => Exception e => e -> m a
```

Thanks!

**Comment by snoyberg** [comment]
Sounds reasonable to me!
