### ISSUE TITLE
Integration into classy-prelude?

### ISSUE THREAD

**Issue by TerrorJack** [fpco/safe-exceptions#7]
Is there a plan for `classy-prelude` to use this library to replace `enclosed-exceptions`, to reduce the cost of combinators like `catchAny` and `tryAny`?

**Comment by snoyberg** [comment]
Actually, yes: https://github.com/snoyberg/classy-prelude/commit/f4d108cf7fe4f8e3e74b21fd614210fcdd6141d7#diff-99157f41e2b53f74864f19716d128fc1L36
